ores:
  COAL_ORE: 0.03
  DEEPSLATE_COAL_ORE: 0.03
  IRON_ORE: 0.04
  DEEPSLATE_IRON_ORE: 0.04
  COPPER_ORE: 0.035
  DEEPSLATE_COPPER_ORE: 0.035
  GOLD_ORE: 0.06
  DEEPSLATE_GOLD_ORE: 0.06
  REDSTONE_ORE: 0.015
  DEEPSLATE_REDSTONE_ORE: 0.015
  LAPIS_ORE: 0.015
  DEEPSLATE_LAPIS_ORE: 0.015
  DIAMOND_ORE: 0.08
  DEEPSLATE_DIAMOND_ORE: 0.08
  EMERALD_ORE: 0.1
  DEEPSLATE_EMERALD_ORE: 0.1
  NETHER_GOLD_ORE: 0.04
  NETHER_QUARTZ_ORE: 0.03
