ores:
  COAL_ORE: 0.01
  DEEPSLATE_COAL_ORE: 0.01
  IRON_ORE: 0.015
  DEEPSLATE_IRON_ORE: 0.015
  COPPER_ORE: 0.01
  DEEPSLATE_COPPER_ORE: 0.01
  GOLD_ORE: 0.02
  DEEPSLATE_GOLD_ORE: 0.02
  REDSTONE_ORE: 0.005
  DEEPSLATE_REDSTONE_ORE: 0.005
  LAPIS_ORE: 0.005
  DEEPSLATE_LAPIS_ORE: 0.005
  DIAMOND_ORE: 0.03
  DEEPSLATE_DIAMOND_ORE: 0.03
  EMERALD_ORE: 0.04
  DEEPSLATE_EMERALD_ORE: 0.04
  NETHER_GOLD_ORE: 0.015
  NETHER_QUARTZ_ORE: 0.01
