name: SJZ_OreReward
version: 1.0
main: com.example.orereward.OreRewardPlugin
api-version: 1.20
folia-supported: true
commands:
  sjz_orereward:
    description: 管理 SJZ_OreReward 插件
    usage: /sjz_orereward <reload|list|debug>
permissions:
  sjzore.admin:
    description: 管理 SJZ_OreReward 插件的權限
    default: op
